import { Box } from "@chakra-ui/react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/legacy/image";

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box position="relative" h="100vh" w="100vw">
        <Image src="/bg-main.jpg" alt="Background Image" layout="fill" objectFit="cover" quality={100} priority />
      </Box>
    </>
  );
}
